repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run all tests
        entry: make test-all
        language: system
        pass_filenames: false
        always_run: true
        
      - id: shellcheck
        name: Run shellcheck
        entry: bash -c 'if command -v shellcheck >/dev/null 2>&1; then make lint; else echo "Shellcheck not found, skipping"; fi'
        language: system
        files: \.(sh)$
        pass_filenames: false

