name: Update Major Version Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  update-major-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update major version tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          MAJOR_VERSION=$(echo $TAG_NAME | sed 's/\.[0-9]*\.[0-9]*$//')
          
          echo "New tag: $TAG_NAME"
          echo "Major version: $MAJOR_VERSION"
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git tag -f $MAJOR_VERSION $TAG_NAME
          git push origin $MAJOR_VERSION --force
          
          echo "Updated $MAJOR_VERSION to point to $TAG_NAME"
          